[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps --ignore-scripts"

[deploy]
startCommand = "node Main.js"
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[environments.production]
NODE_ENV = "production"
